
### The Base Route
GET http://localhost:4500/

###
GET http://localhost:4500/users

###
POST http://localhost:4500/users
Content-Type: application/json

{
  "name": "Riya sharma",
  "age": "19",
  "gender": "female",
  "email": "f@gmail.com"
}

######
###? Deployed Testing-------------------------------------------------------------------------->

GET https://wellnesys-assignment-k7fp.onrender.com/

###
GET https://wellnesys-assignment-k7fp.onrender.com/users

###
POST https://wellnesys-assignment-k7fp.onrender.com/users
Content-Type: application/json

{
  "name": "Rahul Kumar",
  "age": "19",
  "gender": "male",
  "email": "r@gmail.com"
}
